import { IWidget, WidgetGroupId } from "./types.ts";

export const defaultWidgets: IWidget[] = [
  {
    id: "1",
    size: 8,
    visible: true,
    title: "Teslim Edilmeyi Bekleyen Siparişler",
    group: "left",
    lockVisible: true,
    lockDragging: true,
  },
  {
    id: "2",
    size: 4,
    visible: true,
    title: "Duyurularım",
    group: "right",
    lockVisible: true,
    lockDragging: false,
  },
  {
    id: "3",
    size: 8,
    visible: true,
    title: "Haftalık Hak Ediş Tablosu",
    group: "left",
    lockVisible: false,
    lockDragging: false,
  },
  {
    id: "4",
    size: 4,
    visible: true,
    title: "Satış Performansı",
    group: "right",
    lockVisible: true,
    lockDragging: false,
  },
  {
    id: "5",
    size: 12,
    visible: true,
    title: "Ürün Listesi Tablosu",
    group: "bottom",
    lockVisible: false,
    lockDragging: false,
  },
  {
    id: "6",
    size: 12,
    visible: true,
    title: "Kritik Stok Durum Tablosu",
    group: "bottom",
    lockVisible: false,
    lockDragging: false,
  },
  {
    id: "7",
    size: 12,
    visible: true,
    title: "İade Edilen Sipariş Tablosu",
    group: "bottom",
    lockVisible: false,
    lockDragging: false,
  },
  {
    id: "8",
    size: 12,
    visible: true,
    title: "Ürün Tablosu",
    group: "bottom",
    lockVisible: false,
    lockDragging: false,
  },
  {
    id: "9",
    size: 12,
    visible: true,
    title: "Haftanın Görüntülenen Ürünleri",
    group: "bottom",
    lockVisible: false,
    lockDragging: false,
  },
];

export const defaultWidgetGroupIds: WidgetGroupId[] = [
  "left",
  "right",
  "bottom",
];
